[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_url = "${OP_SEPOLIA_RPC_URL}"
sender = "0x6119Cb84698758Bbb9fe9257bF95Ecd7eA8AdF1b"
private_key = "${PRIVATE_KEY}"
etherscan_key = "${ETHERSCAN_API_KEY"
via-ir = true

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
